#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -o pipefail

if [[ -n ${SERVER} ]]; then
  # Require that vdlm_server is running
  if ! netstat -an | grep -P '^\s*tcp\s+\d+\s+\d+\s+0\.0\.0\.0:15555\s+(?>\d{1,3}\.{0,1}){4}:\*\s+LISTEN\s*$' > /dev/null; then
    sleep 1
    if [[ ! ${QUIET_LOGS,,} =~ true ]]; then
      echo "[vdlm_feeder] vdlm_server not running, exiting"
    fi
    exit
  fi

  set -e

  SERVER_ADDR="UDP:${SERVER}:${SERVER_PORT}"
  # shellcheck disable=SC2016
  socat -d TCP:127.0.0.1:15555 "$SERVER_ADDR" \
    2>&1 | stdbuf -oL awk '{print "[vdlm_feeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

  sleep 5
else
  sleep 86400
fi
