#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck disable=SC1091
source /scripts/common

# FEED_ID needs to be set

if [[ -z "${FEED_ID}" ]]; then
	# shellcheck disable=SC2154
	"${s6wrap[@]}"  echo "FEED_ID is not set, exiting"
	exit 1
fi

# FREQUENCIES needs to be set

if [[ -z "${FREQUENCIES}" ]]; then
	"${s6wrap[@]}"  echo "FREQUENCIES is not set, exiting"
	exit 1
fi

IFS=';'
read -ra SPLIT_FREQS <<< "${FREQUENCIES}"

# loop through SPLIT_FREQS

# FREQUENCIES needs to be in the range of 118000000 (118 MHz) - 137000000 (137 MHz).
# Acceptable format is either in Hz (dumpvdl2 default) or in MHz (as with acarsdec)

FREQ_STRING=""
for i in "${SPLIT_FREQS[@]}"
do
	[[ "$i" == *"."* ]] && j="${i/./}000" || j="$i" # convert xxx.xxx (MHz) into Hertz yyyyyy000 if needed
	if [[ $(echo "$j > 118000000" | bc)  -eq 0 || $(echo "$j < 137000000" | bc) -eq 0 ]]; then
		"${s6wrap[@]}"  echo "warning: FREQUENCY $i is not in the range of 118000000 - 137000000 or 118.0 - 137.0"
	fi
	FREQ_STRING+="$j "
done

# Make sure mode is valid

if [[ -n "${SERVER}" && -z "${SERVER_PORT}" ]]; then
	"${s6wrap[@]}"  echo "SERVER is set but SERVER_PORT is not set, exiting"
	exit 1
fi

if [[ -n "$ZMQ_MODE" ]]; then
  if [[ -z "$ZMQ_ENDPOINT" ]]; then
	"${s6wrap[@]}"  echo "ZMQ_MODE mode set to '${ZMQ_MODE}, but ZMQ_ENDPOINT is not set, exiting"
	exit 1
  fi
fi

if [[ -n "$ZMQ_ENDPOINT" ]]; then
  if [[ -z "$ZMQ_MODE" ]]; then
    "${s6wrap[@]}"  echo "ZMQ_ENDPOINT mode set to '${ZMQ_ENDPOINT}, but ZMQ_MODE is not set, exiting"
	exit 1
  fi
fi

mkdir -p /run/acars
touch /run/acars/vdlm.past5min.json

sed -i "s/FREQ_STRING=\"\"/FREQ_STRING=\"$FREQ_STRING\"/g" /etc/s6-overlay/scripts/dumpvdl2

# Everything is good to go. Exit with 0

exit 0
