#!/command/with-contenv bash
#shellcheck shell=bash

# shellcheck disable=SC1091
source /scripts/common

set -e

VDLM_BIN="/usr/local/bin/dumpvdl2"
# shellcheck disable=SC2001
FREQ_STRING=""
VDLM_CMD=()

if [[ -z "${RTL_SERIAL}" ]] && [[ -n "${SERIAL}" ]]; then
    # if RTL_SERIAL not set, use legacy env var SERIAL
    RTL_SERIAL="${SERIAL}"
fi

# Specify device ID
if [ -n "${SOAPYSDR}" ]; then
	VDLM_CMD+=("--soapysdr" "$SOAPYSDR")
    if [[ -n "$SOAPY_DEVICE_SETTINGS" ]]; then
        VDLM_CMD+=("--device-settings" "$SOAPY_DEVICE_SETTINGS")
    fi
elif [[ -n "${RTL_SERIAL}" ]]; then
	VDLM_CMD+=("--rtlsdr" "$RTL_SERIAL")
    if chk_enabled "${BIASTEE}"; then
        VDLM_CMD+=("--bias" "1")
    else
        VDLM_CMD+=("--bias" "0")
    fi
fi

if [ -n "$CENTER_FREQ" ]; then
    VDLM_CMD+=("--centerfreq" "$CENTER_FREQ")
fi

if [ -z "$GAIN" ]; then
    GAIN="40"
fi

if [ -n "$OVERSAMPLE" ]; then
    VDLM_CMD+=("--oversample" "$OVERSAMPLE")
fi

if [ -n "${PPM}" ]; then
	VDLM_CMD+=("--correction" "$PPM")
fi

VDLM_CMD+=("--gain" "$GAIN")

if [[ ${VDLM_FILTER_ENABLE,,} =~ true ]]; then
  VDLM_CMD+=("--msg-filter" "$VDLM_FILTER")
fi

# Send output JSON to vdlm2_server.
VDLM_CMD+=("--station-id=$FEED_ID" "--output" "decoded:json:zmq:mode=server,endpoint=tcp://0.0.0.0:5555")

if [[ -n "$ZMQ_MODE" ]]; then
  if [[ -n "$ZMQ_ENDPOINT" ]]; then
    VDLM_CMD+=("--output" "decoded:json:zmq:mode=${ZMQ_MODE,,},endpoint=${ZMQ_ENDPOINT}")
  fi
fi

if [[ -n "$STATSD_SERVER" ]]; then
  VDLM_CMD+=("--statsd" "$STATSD_SERVER")
fi

# shellcheck disable=SC2206
VDLM_CMD+=($FREQ_STRING)

# shellcheck disable=SC2154
"${s6wrap[@]}" echo "Starting: '$VDLM_BIN" "${VDLM_CMD[*]}'"

if chk_enabled "${QUIET_LOGS}"; then
# shellcheck disable=SC2016
  FILTER_TERMS+=("-e" "\[dumpvdl2\] dumpvdl2 ")
  FILTER_TERMS+=("-e" "Sampling rate set")
  FILTER_TERMS+=("-e" "Found [0-9] device")
  FILTER_TERMS+=("-e" "\[dumpvdl2\]   [0-9]:")
  FILTER_TERMS+=("-e" "\[dumpvdl2\] $")
  FILTER_TERMS+=("-e" "Using device [0-9]:")
  FILTER_TERMS+=("-e" "Found .* tuner")
  FILTER_TERMS+=("-e" "Exact sample rate is:")
  FILTER_TERMS+=("-e" "PLL not locked")
  FILTER_TERMS+=("-e" "Center frequency set")
  FILTER_TERMS+=("-e" "Bandwidth set")
  FILTER_TERMS+=("-e" "Device #[0-9]: gain set to")
  FILTER_TERMS+=("-e" "Device [0-9] bias")
  FILTER_TERMS+=("-e" "Device [0-9] started")
  exec "${s6wrap[@]}" "$VDLM_BIN" "${VDLM_CMD[@]}" > >(grep --line-buffered -v "${FILTER_TERMS[@]}")
else
  # shellcheck disable=SC2016
  exec "${s6wrap[@]}" "$VDLM_BIN" "${VDLM_CMD[@]}"
fi

# if we've ended up here there is a problem!
"${s6wrap[@]}" echo "Exiting with error"
sleep 5
exit 1
