#!/command/with-contenv bash
#shellcheck shell=bash

set -o pipefail

# Require that vdlm_server is running
if ! netstat -an | grep -P '^\s*tcp\s+\d+\s+\d+\s+0\.0\.0\.0:15555\s+(?>\d{1,3}\.{0,1}){4}:\*\s+LISTEN\s*$' > /dev/null; then
  sleep 1
  if [[ ! ${QUIET_LOGS,,} =~ true ]]; then
    echo "[vdlm_stats] vdlm_server not running, exiting"
  fi
  exit
fi

# Start our stats loop
while true; do

  # capture 5 mins of flows
  timeout --foreground 300s socat -u TCP:127.0.0.1:15555 CREATE:/run/acars/vdlm.past5min.json

  # if the port isn't reachable, this file isn't created, either container is shutting down or vdlm_server isn't reachable
  # in both cases let's exit, if this should still be running it will be restarted
  if ! [[ -f /run/acars/vdlm.past5min.json ]]; then
    exit
  fi

  # shellcheck disable=SC2016
  echo "$(sed 's/}{/}\n{/g' /run/acars/vdlm.past5min.json | wc -l) VDLM2 messages received in last 5 mins" | stdbuf -oL awk '{print "[vdlm2_stats] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

  # rotate files keeping last 2 hours
  for i in {24..1}; do
    mv "/run/acars/vdlm.$((i-1)).json" "/run/acars/vdlm.$i.json" > /dev/null 2>&1 || true
  done
  mv "/run/acars/vdlm.past5min.json" "/run/acars/vdlm.0.json" > /dev/null 2>&1 || true

done

sleep 5
